export interface DialogData  {
    id: any,
    name: any,
    description: any,
    image: any,
    price: any,
    priceBeforeDiscount: any,
    available: any,
    orderable: any,
    newItem: any,
    vegetarian: any,
    spicy: any,
    kcl: any,
    calories: any,
    carb: any,
    protein: any,
    fat: any,
    fiber: any,
    sugar: any,
    fish: any,
    nuts: any,
    peanuts: any,
    gluten: any,
    milk: any,
    soya: any,
    shellfish: any,
    eggs: any,
    sesame: any,
    crustacean: any,
    celery: any,
    mustard: any,
    lupins: any,
    sulphite: any,
    extraSections: {
      required: any[],
      optional: any[]
    }
  }
  